import os
import json
from src.ranker import SmartRecruitmentSystem

def generate_outputs():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(base_dir, 'data', 'candidates.csv')
    output_dir = os.path.join(base_dir, 'output')
    os.makedirs(output_dir, exist_ok=True)

    system = SmartRecruitmentSystem(data_path)
    
    query = "Seeking Python Machine Learning Engineer with Scikit-Learn, SQL, and Data Analytics experience."
    ranked = system.rank_candidates(query, top_n=5)

    # Save TXT report
    report_path = os.path.join(output_dir, 'ranking_report.txt')
    with open(report_path, 'w') as f:
        f.write("============================================================\n")
        f.write("    AI SMART RECRUITMENT SYSTEM - CANDIDATE RANKING REPORT   \n")
        f.write("============================================================\n\n")
        f.write(f"JOB QUERY: {query}\n\n")
        f.write(ranked.to_string(index=False))
        f.write("\n\nReport generated by AI-Powered Smart Recruitment Engine.\n")

    # Save JSON summary
    json_path = os.path.join(output_dir, 'ranking_summary.json')
    records = ranked.to_dict(orient='records')
    with open(json_path, 'w') as f:
        json.dump({
            "job_query": query,
            "top_candidates": records
        }, f, indent=4)

    print(f"✔ Generated output report: {report_path}")
    print(f"✔ Generated JSON summary: {json_path}")

if __name__ == "__main__":
    generate_outputs()
